/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: urbanmasque (https://sketchfab.com/urbanmasque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-ad230ec9d8f24bffa7f4a79cc85d5e24
Title: Astronaut
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Astronaut(props) {
  const { nodes, materials } = useGLTF("assets/models/astronaut.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/astronaut.glb");
