/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: R to Restart (https://sketchfab.com/RtoRestart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-bridge-seamless-lowpoly-f2f62b7754d04399aa90af74125edc20
Title: Sci Fi Bridge (Seamless) (LowPoly)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bridge(props) {
  const { nodes, materials } = useGLTF("assets/models/sci_fi_bridge.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Walls}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Columns}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Floor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Columns_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Lights}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Frame}
      />
    </group>
  );
}

useGLTF.preload("assets/models/sci_fi_bridge.glb");
