/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tegnemaskin (https://sketchfab.com/tegnemaskin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-cube-crate-s-4b40fd97b3cb4b68a7b4b18b02b3ec6a
Title: Star Wars Cube Crate S
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function StarWarsCubeCrate(props) {
  const { nodes, materials } = useGLTF("assets/models/starWarsCubeCrate.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["atlas-cube-s_Baked"]}
        position={[-0.027, 0, 0.075]}
      />
    </group>
  );
}

useGLTF.preload("assets/models/starWarsCubeCrate.glb");
