/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function StarWarsDatapad(props) {
  const { nodes, materials } = useGLTF("assets/models/starWarsDatapad.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[-0.011, 0.015, -0.042]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[-0.07, 0.002, 0.121]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.005, 0.014, -0.065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.022, 0.015, -0.065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.009, 0.022, -0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.054, 0.009, 0.071]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[-0.081, 0.002, 0.085]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[-0.081, 0.002, 0.112]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.07, 0.008, 0.085]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["idcs-22-datapad003_Baked001"].geometry}
        material={materials["atlas-idca22"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.led003_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0, 0.005, 0.039]}
        scale={1.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert007_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.009, 0.015, -0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert008_Baked001.geometry}
        material={materials["atlas-idca22"]}
        position={[0.068, 0.007, 0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass004.geometry}
        material={materials["idca-display"]}
        position={[0.008, 0.014, 0.049]}
      />
    </group>
  );
}

useGLTF.preload("assets/models/starWarsDatapad.glb");
