/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: deecube1 (https://sketchfab.com/deecube1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesseract-c6678a45691f43db9ba45573d6f2a407
Title: Tesseract
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Tesseract(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("assets/models/tesseract.glb");
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions["Take 001"].play(); 
  }, [mixer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.549}
        >
          <group
            name="ddf9c6b9132148bfb8a7e2cc5db0fd62fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Geo_Shell"
                  position={[0, 0.254, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.025}
                >
                  <group name="Object_5" position={[0, 0, -10]}>
                    <mesh
                      name="Geo_Shell_Shell_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Geo_Shell_Shell_0.geometry}
                      material={materials.Shell}
                    />
                  </group>
                </group>
                <group
                  name="Geo_core"
                  position={[0, 0.254, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.025}
                >
                  <mesh
                    name="Geo_core_Core_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Geo_core_Core_0.geometry}
                    material={materials.Core}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/tesseract.glb");